
development:
  adapter: postgresql
  encoding: unicode
  database: ninja
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: ninja
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000