
development:
  adapter: postgresql
  encoding: unicode
  database: ninja
  username: postgres
  password: sa2nd4ee8
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: ninja
  username: postgres
  password: sa2nd4ee8
  pool: 5
  timeout: 5000