# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa13a10f87e17c3851b77d67f19681d3f7589562ec1bc0b6f9b355ddf3094bbdd78a7410814018b8bc80c0bab29dcf41d039912096cb84f02e9670024c423382

test:
  secret_key_base: 25d80a7295d3f6ed67c67d34a869850767d4608af7cc7bc3e2731fa7d10b740f4b1f3e46aa9f57cec67466a73be9ab381674a94eb347d50d2de6164365923c13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
